encyclopedia/urls.py
from django.urls import path, re_path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:title>", views.title, name="title"),
    path("<str:title>", views.searching, name="searching"),
    path("create/", views.create, name="create"),
    path("edit/", views.edit, name="edit"),
    path("random/", views.random, name="random"),
    path("wiki/<str:string>", views.wiki, name="wiki"),

]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

#trying to not use models to see if the title can be saved.

#class CreateEntry(models.Model):
    #entry_title = models.CharField(max_length=200)
    #entry_content = models.CharField(max_length=1000)

encyclopedia/views.py
import re
from django.forms import fields, widgets
from django.forms.widgets import HiddenInput, Widget
from django.shortcuts import redirect, render

from . import util
import encyclopedia

import markdown2
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms
import secrets


class TitleSeachForm(forms.Form):
    searched = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': 'Search encyclopedia','autocomplete':'off'})) #attrs={'size': '20'}

class CreateEntryForm(forms.Form):
    entry_title = forms.CharField(label="Enter entry title", max_length=100, widget=forms.TextInput(attrs={'autocomplete':'off'}))
    entry_content = forms.CharField(label=False, widget=forms.Textarea(attrs={'placeholder': 'Enter entry content here', 'autocomplete':'off'}))

class EditEntryForm(forms.Form):
    entry_content = forms.CharField(label=False, widget=forms.Textarea(attrs={'placeholder': 'Enter entry content here', 'autocomplete':'off'}))


def index(request):
    if request.method == "POST":
        form = TitleSeachForm(request.POST)
        if form.is_valid():
            searched = form.cleaned_data["searched"]
            return redirect(f"title.html?title={searched}")
        else:
            return render(request, "index.html", {
                "form" : form
            })   
    else:
        form = TitleSeachForm()
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries(),
            "form":TitleSeachForm()
        })

def title(request, title):
    if request.method=='GET':
        title = request.GET.get('title')

    entries = util.list_entries()
    partial_match = [x for x in entries if str(title) in x] #casting to string to avoid error message
    if title in entries:
        raw_content = util.get_entry(title)
        content = markdown2.markdown(raw_content)
        return render(request, "encyclopedia/title.html", {
            "title": title,
            "content" : content,
            "form":TitleSeachForm()
        })
    # Here I need to test if the title matches partially an entry
    elif partial_match:
        list_of_matches = partial_match
        return render(request, "encyclopedia/searching.html", {
            "matches": list_of_matches,
            "form":TitleSeachForm()
        })

    else:
        #return render(request, "encyclopedia/notfound.html", {
        return render(request, "encyclopedia/searching.html", {
             "title": title,
             "form":TitleSeachForm()
        })

def searching(request, title):
    if request.method=='GET':
        title = request.GET.get('title')
        entries = util.list_entries()
        if title in entries:
            raw_content = util.get_entry(title)
            content = markdown2.markdown(raw_content)
            return render(request, "encyclopedia/search.html", {
                "title": title,
                "content" : content
            })
        else:
            return render(request, "encyclopedia/search.html", {
                "title": title
            })

def create(request):
    if request.method=='POST':
        form = CreateEntryForm(request.POST)
        if form.is_valid():
            entry_title = form.cleaned_data['entry_title']
            entry_content = form.cleaned_data['entry_content']
            entries = util.list_entries()
            if entry_title in entries:
                return render(request, "encyclopedia/error.html", {
                    "entry": entry_title,
                    "form":TitleSeachForm()
                })
            else:
                save_entry = util.save_entry(entry_title, entry_content)
                raw_content = util.get_entry(entry_title)
                content = markdown2.markdown(raw_content)
                return render(request, "encyclopedia/title.html", {
                    "title": entry_title,
                    "content" : content
                })
    else:
        return render(request, "encyclopedia/create.html", {
            "form":TitleSeachForm(),
            "form2":CreateEntryForm()
                })

def edit(request):
    if request.method=='GET':
        entry_title = request.GET.get('entry_title')
        raw_content = util.get_entry(entry_title)
        entry_content = markdown2.markdown(raw_content)
        return render(request, "encyclopedia/edit.html", {
                "entry_title": entry_title,
                "form3": EditEntryForm(initial={'entry_content':raw_content}),
                "form":TitleSeachForm()
                }) 
    else:
        form = EditEntryForm(request.POST)
        if form.is_valid():
            entry_title = request.POST.get('entry_title')
            entry_content = form.cleaned_data['entry_content']
            save_entry = util.save_entry(entry_title, entry_content)
            raw_content = util.get_entry(entry_title)
            content = markdown2.markdown(raw_content)
            return render(request, "encyclopedia/title.html", {
                "title": entry_title,
                "content" : content
            })

def random(request):
    if request.method=='GET':
        entries = util.list_entries()
        if entries:
            selected_title = secrets.choice(entries)
            raw_content = util.get_entry(selected_title)
            content = markdown2.markdown(raw_content)
            return render(request, "encyclopedia/title.html", {
                "title": selected_title,
                "content" : content,
                "form":TitleSeachForm()
            })
    else:
        return render(request, "encyclopedia/index.html", {
             "form":TitleSeachForm()
        })

def wiki(request, string):
    if request.method=='GET':
        title = string
        entries = util.list_entries()
        if title in entries:
            raw_content = util.get_entry(title)
            content = markdown2.markdown(raw_content)
            return render(request, "encyclopedia/title.html", {
                "title": title,
                "content" : content,
                "form":TitleSeachForm() 
            })
        else:
            return render(request, "encyclopedia/searching.html", {
                "title": title,
                "form":TitleSeachForm()
            })

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}


{% block title %}
        
    Create

{% endblock %}

{% block body %}

    <h1>Create a new entry</h1><br>
    <!--{% csrf_token %}-->
    <form action="{% url 'encyclopedia:create' %}" method="post" "> <!--enctype="multipart/form-data-->
        {% csrf_token %}
        {{ form2 }}
        <input type="submit" name="create_entry" value="Submit entry">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}


{% block title %}
        
    Edit

{% endblock %}

{% block body %}

    <h1>Edit this entry: "{{ entry_title }}"</h1>



    <form action="{% url 'encyclopedia:edit' %}" method="post"> 
        {% csrf_token %}
        {{ form3 }}
        <input type="hidden" name="entry_title" value="{{ entry_title }}">
        <input type="submit" value="Click here to save your changes">
    </form>


{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}


{% block title %}
        
    Error

{% endblock %}

{% block body %}

    <h1>Error</h1><br>
    <h3>The entry for "{{ entry }}" already exist in the encyclopedia</h3>
    

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>


    <ul>
        {% for entry in entries %}
            <li><a href="title.html?title={{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:index' %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit", value="Search">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/notfound.html
{% extends "encyclopedia/layout.html" %}


{% block title %}
        
    Not found

{% endblock %}

{% block body %}

    <h1>Error</h1><br>
    <h3>The entry you are looking for does not yet exist</h3>
    {{ title }}

{% endblock %}

encyclopedia/templates/encyclopedia/random.html
{% extends "encyclopedia/layout.html" %}


{% block title %}
        
    Random

{% endblock %}

{% block body %}

    {{ content|safe }}<br>
    <div>
        <form method="get" action="{% url 'encyclopedia:edit' %}">
            {% csrf_token %}
            <input type="hidden" name="entry_title" value="{{ title }}"">
            <!--<input type="hidden" name="entry_content" value="{{ content }}">-->
            <button type="submit" name="edit_post_requ">
              Edit this entry
            </button>
          </form>
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/searching.html
{% extends "encyclopedia/layout.html" %}


{% block title %}
        
    {{ title }}

{% endblock %}

{% block body %}

    <h1>Search results</h1><br>
    <ul>
        {% for entry in matches %}
            <li><a href="title.html?title={{ entry }}">{{ entry }}</a></li>
        {% empty %}
            <li>Sorry, your search did not match any entry.</li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/title.html
{% extends "encyclopedia/layout.html" %}


{% block title %}
        
    {{ title }}

{% endblock %}

{% block body %}

    {{ content|safe }}<br>
    <div>
        <form method="get" action="{% url 'encyclopedia:edit' %}">
            {% csrf_token %}
            <input type="hidden" name="entry_title" value="{{ title }}"">
            <button type="submit" name="edit_post_requ">
              Edit this entry
            </button>
          </form>
    </div>

{% endblock %}